# Generated by Django 2.2.10 on 2021-05-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210511_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответы', 'verbose_name_plural': 'Ответ'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['title'], 'verbose_name': 'Варианты', 'verbose_name_plural': 'Вариант'},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='User',
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
