# Generated by Django 2.2.10 on 2021-05-13 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210512_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='choices',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Choice'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='choices_text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
